<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyVersion>0.9.9.20</AssemblyVersion>
		<FileVersion>0.9.9.20</FileVersion>
		<Version>0.9.9.20</Version>
		<ProductVersion>0.9.9.20</ProductVersion>
		<AssemblyTitle>DBF</AssemblyTitle>
		<AssemblyName>DBF</AssemblyName>
		<Description>DBF Tools - Viser Start og resultatlister og 1-4 bruidgeure</Description>
		<RootNamespace>DBF</RootNamespace>
		<Company>Morten Sparding</Company>
		<Product>DBF Tools</Product>
		<Copyright>Copyright © 2025</Copyright>	
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>false</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<LangVersion>latest</LangVersion>
		<Platforms>AnyCPU;x64</Platforms>
		<ApplicationIcon>Images\DBF_Tools.ico</ApplicationIcon>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<ComVisible>false</ComVisible>
		<Guid>8e71374d-fd18-4298-8e6b-816e21df3aa8</Guid>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>	
	  <None Remove="Views\AboutView.axaml" />
	  <None Remove="Views\ConfigurationView.axaml" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="AssemblyInfo.cs" />
		<Compile Remove="AudioFiles\AudioPlayer.cs" />
		<Compile Remove="AudioFiles\AudioServices\LibVlcAudioService.cs" />
		<Compile Remove="BridgeMateModel\AccessContext.cs" />
		<Compile Remove="Helpers\CrashDetector.cs" />
		<Compile Remove="ViewModels\ProjectorViewModel.cs" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Images\DBF_Tools.ico">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>

		<Resource Include="Images\guideTilUr.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>

		<EmbeddedResource Include="Images\projector_48x48.ico" />
	</ItemGroup>

	<ItemGroup>
		<SplashScreen Include="Images\Splash.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</SplashScreen>
	</ItemGroup>


	<ItemGroup>
		<!--<ProjectReference Include="..\..\Common Libs\Caliburn.Micro4\src\Caliburn.Micro.Core\Caliburn.Micro.Core.csproj" />
			<ProjectReference Include="..\..\Common Libs\Caliburn.Micro4\src\Caliburn.Micro.Platform.Core\Caliburn.Micro.Platform.Core.csproj" />
			<ProjectReference Include="..\..\Common Libs\Caliburn.Micro4\src\Caliburn.Micro.Platform\Caliburn.Micro.Platform.csproj" />-->

		<PackageReference Include="Caliburn.Micro" Version="4.0.230" />
		<PackageReference Include="Caliburn.Micro.Core" Version="4.0.230" />
	
	</ItemGroup>

	<ItemGroup>	
		<PackageReference Include="Fody" Version="6.9.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
			<PackageReference Include="PropertyChanged.Fody" Version="4.1.0">
				<PrivateAssets>all</PrivateAssets>
			</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<!--Bemærk, at CDATA ADO.Net her kun virker med entity framework 6 og åbenbart også 8:-) -->
		<!--<Reference Include="CData.EntityFrameworkCore.Access">
			<HintPath>C:\Program Files\CData\CData ADO.NET Provider for Microsoft Access 2024\lib\net8.0\EFCORE80\CData.EntityFrameworkCore.Access.dll</HintPath>
		</Reference>

		<Reference Include="System.Data.CData.Access">
			<HintPath>C:\Program Files\CData\CData ADO.NET Provider for Microsoft Access 2024\lib\net8.0\System.Data.CData.Access.dll</HintPath>
		</Reference>-->

		<PackageReference Include="CData.Access" Version="24.0.9175" />
		<PackageReference Include="CData.Access.EntityFrameworkCore" Version="24.0.9175" />
	</ItemGroup>


	<ItemGroup>
		<!--<PackageReference Include="Baksteen.Extensions.DeepCopy" Version="1.0.4" />-->
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.1" />
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="NetCoreAudio" Version="2.0.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="System.Management" Version="9.0.9" /> <!--Must match the version in Github Updater-->
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
		<PackageReference Include="WpfScreenHelper" Version="2.1.1" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="syncfusion.ui.wpf.net" Version="31.1.19" />
		<PackageReference Include="Syncfusion.SfBusyIndicator.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.SfGrid.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Shared.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Shared.Base" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Grid.Wpf" Version="31.1.19" />
		<PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Themes.FluentLight.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Themes.MaterialDark.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Themes.Office2019Colorful.WPF" Version="31.1.19" />
		<PackageReference Include="Syncfusion.Tools.WPF" Version="31.1.19" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\PublishProfiles\" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>

		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="Images\projector.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		
		<None Update="Images\projector_48x48.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>

		<Content Include="..\..\SyncfusionLicense.txt" Link="SyncfusionLicense.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<None Include="..\..\System.Data.CData.Access.lic" Link="System.Data.CData.Access.lic">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Include="FodyWeavers.xsd" />

		<ProjectReference Include="..\..\Common Libs\AppArguments\AppArguments.csproj" />

		<ProjectReference Include="..\..\Common Libs\GithubTools\GithubTools.csproj" />
		
		<None Update="InstallerFiles\AccessDatabaseEngine_2010_x86.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
