//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBF.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About DBF Tools.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Timer.
        /// </summary>
        internal static string AddTimer {
            get {
                return ResourceManager.GetString("AddTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string appSettings {
            get {
                return ResourceManager.GetString("appSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A prior section.
        /// </summary>
        internal static string aPriorSection {
            get {
                return ResourceManager.GetString("aPriorSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BackgroundColor_Blue {
            get {
                return ResourceManager.GetString("BackgroundColor_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string BackgroundColor_Green {
            get {
                return ResourceManager.GetString("BackgroundColor_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string BackgroundColor_Orange {
            get {
                return ResourceManager.GetString("BackgroundColor_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string BackgroundColor_Red {
            get {
                return ResourceManager.GetString("BackgroundColor_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string BackgroundColor_White {
            get {
                return ResourceManager.GetString("BackgroundColor_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC3 data.
        /// </summary>
        internal static string BC3Data {
            get {
                return ResourceManager.GetString("BC3Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC3 data for.
        /// </summary>
        internal static string BC3DataFor {
            get {
                return ResourceManager.GetString("BC3DataFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC3 data not uploaded.
        /// </summary>
        internal static string BC3NotUploaded {
            get {
                return ResourceManager.GetString("BC3NotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the start or resultlist.
        /// </summary>
        internal static string BC3ReadError {
            get {
                return ResourceManager.GetString("BC3ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boards.
        /// </summary>
        internal static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break After Round.
        /// </summary>
        internal static string BreakAfterRound {
            get {
                return ResourceManager.GetString("BreakAfterRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Message.
        /// </summary>
        internal static string BreakMessage {
            get {
                return ResourceManager.GetString("BreakMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Minutes.
        /// </summary>
        internal static string BreakMinutes {
            get {
                return ResourceManager.GetString("BreakMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get data from the terminals.
        /// </summary>
        internal static string BridgeMateError {
            get {
                return ResourceManager.GetString("BridgeMateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Timers.
        /// </summary>
        internal static string BridgeTimers {
            get {
                return ResourceManager.GetString("BridgeTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string btnSaveAndClose {
            get {
                return ResourceManager.GetString("btnSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Timers.
        /// </summary>
        internal static string btnShowBridgeTimers {
            get {
                return ResourceManager.GetString("btnShowBridgeTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Results.
        /// </summary>
        internal static string btnShowResults {
            get {
                return ResourceManager.GetString("btnShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Startlists.
        /// </summary>
        internal static string btnShowStartLists {
            get {
                return ResourceManager.GetString("btnShowStartLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset and Close.
        /// </summary>
        internal static string btnYesAndReset {
            get {
                return ResourceManager.GetString("btnYesAndReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as one group.
        /// </summary>
        internal static string chkShowAsOneGroup {
            get {
                return ResourceManager.GetString("chkShowAsOneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the Timer will reset it. Do you want to continue?.
        /// </summary>
        internal static string CloseAndResetWarning {
            get {
                return ResourceManager.GetString("CloseAndResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the window will reset alle the timers..
        /// </summary>
        internal static string ClosingTheWindow {
            get {
                return ResourceManager.GetString("ClosingTheWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Preset.
        /// </summary>
        internal static string CreateNewPreset {
            get {
                return ResourceManager.GetString("CreateNewPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        internal static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBF Projector.
        /// </summary>
        internal static string DBFProjector {
            get {
                return ResourceManager.GetString("DBFProjector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Preset.
        /// </summary>
        internal static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a simple app offers up to four bridge timers that can be controlled on the pc, at optional displayed on an second monitor or projector.&amp;#10; It can be read a corresponding BridgeMate database and update the timers accordantly and in Denmark it&apos;s also possible to Start and Result lists from BC3&apos;s output. .
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist.
        /// </summary>
        internal static string DoNotExist {
            get {
                return ResourceManager.GetString("DoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Greeting Bottom.
        /// </summary>
        internal static string EndGreetingBottom {
            get {
                return ResourceManager.GetString("EndGreetingBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Greeting Top.
        /// </summary>
        internal static string EndGreetingTop {
            get {
                return ResourceManager.GetString("EndGreetingTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deserializing file.
        /// </summary>
        internal static string ErrorDeserializing {
            get {
                return ResourceManager.GetString("ErrorDeserializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate  executable file.
        /// </summary>
        internal static string ErrorExecutableFileMissing {
            get {
                return ResourceManager.GetString("ErrorExecutableFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error opening/handling the file.
        /// </summary>
        internal static string ErrorFile {
            get {
                return ResourceManager.GetString("ErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading Main.xml file.
        /// </summary>
        internal static string ErrorMainXml {
            get {
                return ResourceManager.GetString("ErrorMainXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing sound.
        /// </summary>
        internal static string ErrorPlayingSound {
            get {
                return ResourceManager.GetString("ErrorPlayingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading BridgeMate folder.
        /// </summary>
        internal static string ErrorReadingBrideMateFolder {
            get {
                return ResourceManager.GetString("ErrorReadingBrideMateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading start or result lists.
        /// </summary>
        internal static string ErrorReadingStartOrResultLists {
            get {
                return ResourceManager.GetString("ErrorReadingStartOrResultLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart error.
        /// </summary>
        internal static string ErrorRestart {
            get {
                return ResourceManager.GetString("ErrorRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E/W.
        /// </summary>
        internal static string EW {
            get {
                return ResourceManager.GetString("EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end time.
        /// </summary>
        internal static string ExpectedEndTime {
            get {
                return ResourceManager.GetString("ExpectedEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Playing Time.
        /// </summary>
        internal static string ExpectedPlayingTime {
            get {
                return ResourceManager.GetString("ExpectedPlayingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Colors.
        /// </summary>
        internal static string FavoriteColers {
            get {
                return ResourceManager.GetString("FavoriteColers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Half.
        /// </summary>
        internal static string FirstHalf {
            get {
                return ResourceManager.GetString("FirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfs.
        /// </summary>
        internal static string Halfs {
            get {
                return ResourceManager.GetString("Halfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained %.
        /// </summary>
        internal static string hdActualPct {
            get {
                return ResourceManager.GetString("hdActualPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imps.
        /// </summary>
        internal static string hdActualScore {
            get {
                return ResourceManager.GetString("hdActualScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔHac.
        /// </summary>
        internal static string hdDeltaHac {
            get {
                return ResourceManager.GetString("hdDeltaHac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        internal static string hdExpectedScore {
            get {
                return ResourceManager.GetString("hdExpectedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grp.
        /// </summary>
        internal static string hdGroup {
            get {
                return ResourceManager.GetString("hdGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hac.
        /// </summary>
        internal static string hdHAC {
            get {
                return ResourceManager.GetString("hdHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hac grp.
        /// </summary>
        internal static string hdHACGroup {
            get {
                return ResourceManager.GetString("hdHACGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hac pos.
        /// </summary>
        internal static string hdHacPos {
            get {
                return ResourceManager.GetString("hdHacPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hac #.
        /// </summary>
        internal static string hdHACRank {
            get {
                return ResourceManager.GetString("hdHACRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imps.
        /// </summary>
        internal static string hdImps {
            get {
                return ResourceManager.GetString("hdImps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP.
        /// </summary>
        internal static string hdKP {
            get {
                return ResourceManager.GetString("hdKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP Total.
        /// </summary>
        internal static string hdKPTotal {
            get {
                return ResourceManager.GetString("hdKPTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        internal static string hdMP {
            get {
                return ResourceManager.GetString("hdMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        internal static string hdNames {
            get {
                return ResourceManager.GetString("hdNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string hdNo {
            get {
                return ResourceManager.GetString("hdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps..
        /// </summary>
        internal static string hdOpponentTeam {
            get {
                return ResourceManager.GetString("hdOpponentTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string hdPlayers {
            get {
                return ResourceManager.GetString("hdPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string hdPos {
            get {
                return ResourceManager.GetString("hdPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string hdPosition {
            get {
                return ResourceManager.GetString("hdPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string hdRanking {
            get {
                return ResourceManager.GetString("hdRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string hdResult {
            get {
                return ResourceManager.GetString("hdResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string hdScore {
            get {
                return ResourceManager.GetString("hdScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string hdSection {
            get {
                return ResourceManager.GetString("hdSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seating.
        /// </summary>
        internal static string hdStartPos {
            get {
                return ResourceManager.GetString("hdStartPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub group.
        /// </summary>
        internal static string hdSubGroup {
            get {
                return ResourceManager.GetString("hdSubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string hdTeam {
            get {
                return ResourceManager.GetString("hdTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        internal static string hdTournament {
            get {
                return ResourceManager.GetString("hdTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        internal static string hdTournamentPos {
            get {
                return ResourceManager.GetString("hdTournamentPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string hdTournamentScore {
            get {
                return ResourceManager.GetString("hdTournamentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP.
        /// </summary>
        internal static string hpKp {
            get {
                return ResourceManager.GetString("hpKp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in path.
        /// </summary>
        internal static string InPath {
            get {
                return ResourceManager.GetString("InPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Round!.
        /// </summary>
        internal static string LastRound {
            get {
                return ResourceManager.GetString("LastRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the red values from the BridgeMate Server?.
        /// </summary>
        internal static string MarkedValues {
            get {
                return ResourceManager.GetString("MarkedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rows in window:.
        /// </summary>
        internal static string MaxRows {
            get {
                return ResourceManager.GetString("MaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes break after.
        /// </summary>
        internal static string MinutesBreakAfter {
            get {
                return ResourceManager.GetString("MinutesBreakAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound file was not found.
        /// </summary>
        internal static string MissingSoundFile {
            get {
                return ResourceManager.GetString("MissingSoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing startlist in.
        /// </summary>
        internal static string MissingStartlist {
            get {
                return ResourceManager.GetString("MissingStartlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Timers.
        /// </summary>
        internal static string mnuBridgeTimers {
            get {
                return ResourceManager.GetString("mnuBridgeTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Program Version.
        /// </summary>
        internal static string mnuChangeProgramVersion {
            get {
                return ResourceManager.GetString("mnuChangeProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen mode.
        /// </summary>
        internal static string mnuFullscreen {
            get {
                return ResourceManager.GetString("mnuFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open JSON settings.
        /// </summary>
        internal static string mnuOpenJsonSettings {
            get {
                return ResourceManager.GetString("mnuOpenJsonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logfile.
        /// </summary>
        internal static string mnuOpenLogFile {
            get {
                return ResourceManager.GetString("mnuOpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program saving the timer states.
        /// </summary>
        internal static string mnuRestartAndPreserveTimers {
            get {
                return ResourceManager.GetString("mnuRestartAndPreserveTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        internal static string mnuSettings {
            get {
                return ResourceManager.GetString("mnuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dansk.
        /// </summary>
        internal static string mnuToggleLanguage {
            get {
                return ResourceManager.GetString("mnuToggleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string mnuView {
            get {
                return ResourceManager.GetString("mnuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give it a name.
        /// </summary>
        internal static string NameIt {
            get {
                return ResourceManager.GetString("NameIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Setting.
        /// </summary>
        internal static string NewSetting {
            get {
                return ResourceManager.GetString("NewSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not uploaded.
        /// </summary>
        internal static string NotUploaded {
            get {
                return ResourceManager.GetString("NotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/S.
        /// </summary>
        internal static string NS {
            get {
                return ResourceManager.GetString("NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause until.
        /// </summary>
        internal static string PauseUntil {
            get {
                return ResourceManager.GetString("PauseUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setting with the same name already exists.
        /// </summary>
        internal static string PresetAlreadyExists {
            get {
                return ResourceManager.GetString("PresetAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projector.
        /// </summary>
        internal static string Projector {
            get {
                return ResourceManager.GetString("Projector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling frekvens on projector:.
        /// </summary>
        internal static string ProjectorInterval {
            get {
                return ResourceManager.GetString("ProjectorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Start- and Result list:.
        /// </summary>
        internal static string ReadBC3 {
            get {
                return ResourceManager.GetString("ReadBC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read BridgeMate status:.
        /// </summary>
        internal static string ReadBM {
            get {
                return ResourceManager.GetString("ReadBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remember to clean up on and around the table.
        /// </summary>
        internal static string RememberToCleanUp {
            get {
                return ResourceManager.GetString("RememberToCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the Timer will restore the saved setting.
        /// </summary>
        internal static string ResetTimers {
            get {
                return ResourceManager.GetString("ResetTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the Timers will restore the saved settings.
        /// </summary>
        internal static string ResetTimersPlural {
            get {
                return ResourceManager.GetString("ResetTimersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        internal static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        internal static string SavePreset {
            get {
                return ResourceManager.GetString("SavePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the settings.
        /// </summary>
        internal static string SaveSettingsQuestion {
            get {
                return ResourceManager.GetString("SaveSettingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Half.
        /// </summary>
        internal static string SecondHalf {
            get {
                return ResourceManager.GetString("SecondHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not Completed or not uploaded.
        /// </summary>
        internal static string SectionNotCompletedOrNotSent {
            get {
                return ResourceManager.GetString("SectionNotCompletedOrNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Clock.
        /// </summary>
        internal static string SetClock {
            get {
                return ResourceManager.GetString("SetClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startlist.
        /// </summary>
        internal static string Startlist {
            get {
                return ResourceManager.GetString("Startlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubClub.
        /// </summary>
        internal static string Subclub {
            get {
                return ResourceManager.GetString("Subclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Match.
        /// </summary>
        internal static string TeamMatch {
            get {
                return ResourceManager.GetString("TeamMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the peace and order..
        /// </summary>
        internal static string ThanksForNow {
            get {
                return ResourceManager.GetString("ThanksForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section dated.
        /// </summary>
        internal static string theSectionDate {
            get {
                return ResourceManager.GetString("theSectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset the timer..
        /// </summary>
        internal static string ThisWillResetTheTimer {
            get {
                return ResourceManager.GetString("ThisWillResetTheTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Per Round.
        /// </summary>
        internal static string TimePerRound {
            get {
                return ResourceManager.GetString("TimePerRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Settings.
        /// </summary>
        internal static string TimerSettings {
            get {
                return ResourceManager.GetString("TimerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the timer.
        /// </summary>
        internal static string tipCloseTimer {
            get {
                return ResourceManager.GetString("tipCloseTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce time for this round. Hold down the shift key to reduce time on all the watches.
        /// </summary>
        internal static string tipLessTime {
            get {
                return ResourceManager.GetString("tipLessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the time for this round. Hold down the shift key to increase time on all the timers.
        /// </summary>
        internal static string tipMoreTime {
            get {
                return ResourceManager.GetString("tipMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move timer down.
        /// </summary>
        internal static string tipMoveTimerDown {
            get {
                return ResourceManager.GetString("tipMoveTimerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the timer up.
        /// </summary>
        internal static string tipMoveTimerUp {
            get {
                return ResourceManager.GetString("tipMoveTimerUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next round. Hold down the shift key to go to next round on all the timers.
        /// </summary>
        internal static string tipNextRound {
            get {
                return ResourceManager.GetString("tipNextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the timer. Hold down the shift key to pause all timers.
        /// </summary>
        internal static string tipPauseTimer {
            get {
                return ResourceManager.GetString("tipPauseTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the timer. Hold down the shift key to reset all the timers.
        /// </summary>
        internal static string tipResetTimer {
            get {
                return ResourceManager.GetString("tipResetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the round. Hold down the Shift key to restart the round on all timers.
        /// </summary>
        internal static string tipRestartTimer {
            get {
                return ResourceManager.GetString("tipRestartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the timer.
        /// </summary>
        internal static string tipStartTimer {
            get {
                return ResourceManager.GetString("tipStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer setup.
        /// </summary>
        internal static string tipTimerSetup {
            get {
                return ResourceManager.GetString("tipTimerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition to.
        /// </summary>
        internal static string TransitioningTo {
            get {
                return ResourceManager.GetString("TransitioningTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Time.
        /// </summary>
        internal static string TransitionTime {
            get {
                return ResourceManager.GetString("TransitionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unfinished.
        /// </summary>
        internal static string UnfinishedSection {
            get {
                return ResourceManager.GetString("UnfinishedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format.
        /// </summary>
        internal static string UnknownFormat {
            get {
                return ResourceManager.GetString("UnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Preset.
        /// </summary>
        internal static string UsePreset {
            get {
                return ResourceManager.GetString("UsePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Vis_Start {
            get {
                return ResourceManager.GetString("Vis Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Start New Game Warning.
        /// </summary>
        internal static string WarningDoNotStartNewGames {
            get {
                return ResourceManager.GetString("WarningDoNotStartNewGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are playing.
        /// </summary>
        internal static string WeArePlaying {
            get {
                return ResourceManager.GetString("WeArePlaying", resourceCulture);
            }
        }
    }
}
