//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_Shared_Wpf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_Shared_Wpf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Syncfusion.Shared.Wpf", typeof(Syncfusion_Shared_Wpf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string AccessCalendarText {
            get {
                return ResourceManager.GetString("AccessCalendarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        internal static string AccessClockText {
            get {
                return ResourceManager.GetString("AccessClockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string AccessEmptyDateText {
            get {
                return ResourceManager.GetString("AccessEmptyDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today .
        /// </summary>
        internal static string AccessTodayText {
            get {
                return ResourceManager.GetString("AccessTodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string AccessWatchText {
            get {
                return ResourceManager.GetString("AccessWatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice Blue.
        /// </summary>
        internal static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string AlphaTooltipText {
            get {
                return ResourceManager.GetString("AlphaTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique White.
        /// </summary>
        internal static string AntiqueWhite {
            get {
                return ResourceManager.GetString("AntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        internal static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine.
        /// </summary>
        internal static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string AText {
            get {
                return ResourceManager.GetString("AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string AutomaticText {
            get {
                return ResourceManager.GetString("AutomaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundText {
            get {
                return ResourceManager.GetString("BackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisque.
        /// </summary>
        internal static string Bisque {
            get {
                return ResourceManager.GetString("Bisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanched Almond.
        /// </summary>
        internal static string BlanchedAlmond {
            get {
                return ResourceManager.GetString("BlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string BlueTooltipText {
            get {
                return ResourceManager.GetString("BlueTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Violet.
        /// </summary>
        internal static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright.
        /// </summary>
        internal static string BrightText {
            get {
                return ResourceManager.GetString("BrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BurlyWood.
        /// </summary>
        internal static string BurlyWood {
            get {
                return ResourceManager.GetString("BurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet Blue.
        /// </summary>
        internal static string CadetBlue {
            get {
                return ResourceManager.GetString("CadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chartreuse.
        /// </summary>
        internal static string Chartreuse {
            get {
                return ResourceManager.GetString("Chartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseTooltip {
            get {
                return ResourceManager.GetString("CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Models:.
        /// </summary>
        internal static string ColorModelsText {
            get {
                return ResourceManager.GetString("ColorModelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors:.
        /// </summary>
        internal static string ColorsText {
            get {
                return ResourceManager.GetString("ColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral.
        /// </summary>
        internal static string Coral {
            get {
                return ResourceManager.GetString("Coral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornflower Blue.
        /// </summary>
        internal static string CornflowerBlue {
            get {
                return ResourceManager.GetString("CornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corn Silk.
        /// </summary>
        internal static string CornSilk {
            get {
                return ResourceManager.GetString("CornSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson.
        /// </summary>
        internal static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string CurrentText {
            get {
                return ResourceManager.GetString("CurrentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        internal static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Cyan.
        /// </summary>
        internal static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkerText {
            get {
                return ResourceManager.GetString("DarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Goldenrod.
        /// </summary>
        internal static string DarkGoldenrod {
            get {
                return ResourceManager.GetString("DarkGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Gray.
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green.
        /// </summary>
        internal static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Khaki.
        /// </summary>
        internal static string DarkKhaki {
            get {
                return ResourceManager.GetString("DarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Magenta.
        /// </summary>
        internal static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark OliveGreen.
        /// </summary>
        internal static string DarkOliveGreen {
            get {
                return ResourceManager.GetString("DarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orange.
        /// </summary>
        internal static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Orchid.
        /// </summary>
        internal static string DarkOrchid {
            get {
                return ResourceManager.GetString("DarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        internal static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Salmon.
        /// </summary>
        internal static string DarkSalmon {
            get {
                return ResourceManager.GetString("DarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark SeaGreen.
        /// </summary>
        internal static string DarkSeaGreen {
            get {
                return ResourceManager.GetString("DarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark SlateBlue.
        /// </summary>
        internal static string DarkSlateBlue {
            get {
                return ResourceManager.GetString("DarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark SlateGray.
        /// </summary>
        internal static string DarkSlateGray {
            get {
                return ResourceManager.GetString("DarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Turquoise.
        /// </summary>
        internal static string DarkTurquoise {
            get {
                return ResourceManager.GetString("DarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Violet.
        /// </summary>
        internal static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Pink.
        /// </summary>
        internal static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep SkyBlue.
        /// </summary>
        internal static string DeepSkyBlue {
            get {
                return ResourceManager.GetString("DeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim Gray.
        /// </summary>
        internal static string DimGray {
            get {
                return ResourceManager.GetString("DimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodger Blue.
        /// </summary>
        internal static string DodgerBlue {
            get {
                return ResourceManager.GetString("DodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Point.
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebrick.
        /// </summary>
        internal static string Firebrick {
            get {
                return ResourceManager.GetString("Firebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floral White.
        /// </summary>
        internal static string FloralWhite {
            get {
                return ResourceManager.GetString("FloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Green.
        /// </summary>
        internal static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchsia.
        /// </summary>
        internal static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainsboro.
        /// </summary>
        internal static string Gainsboro {
            get {
                return ResourceManager.GetString("Gainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost White.
        /// </summary>
        internal static string GhostWhite {
            get {
                return ResourceManager.GetString("GhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldenrod.
        /// </summary>
        internal static string Goldenrod {
            get {
                return ResourceManager.GetString("Goldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Origin.
        /// </summary>
        internal static string GradientOrigin {
            get {
                return ResourceManager.GetString("GradientOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string GreenTooltipText {
            get {
                return ResourceManager.GetString("GreenTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Yellow.
        /// </summary>
        internal static string GreenYellow {
            get {
                return ResourceManager.GetString("GreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeydew.
        /// </summary>
        internal static string Honeydew {
            get {
                return ResourceManager.GetString("Honeydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotPink.
        /// </summary>
        internal static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        internal static string HSV {
            get {
                return ResourceManager.GetString("HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue..
        /// </summary>
        internal static string HueTooltipText {
            get {
                return ResourceManager.GetString("HueTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string Ice {
            get {
                return ResourceManager.GetString("Ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndianRed.
        /// </summary>
        internal static string IndianRed {
            get {
                return ResourceManager.GetString("IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory.
        /// </summary>
        internal static string Ivory {
            get {
                return ResourceManager.GetString("Ivory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaki.
        /// </summary>
        internal static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        internal static string Lavender {
            get {
                return ResourceManager.GetString("Lavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender Blush.
        /// </summary>
        internal static string LavenderBlush {
            get {
                return ResourceManager.GetString("LavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawn Green.
        /// </summary>
        internal static string LawnGreen {
            get {
                return ResourceManager.GetString("LawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon Chiffon.
        /// </summary>
        internal static string LemonChiffon {
            get {
                return ResourceManager.GetString("LemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Coral.
        /// </summary>
        internal static string LightCoral {
            get {
                return ResourceManager.GetString("LightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Cyan.
        /// </summary>
        internal static string LightCyan {
            get {
                return ResourceManager.GetString("LightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LighterText {
            get {
                return ResourceManager.GetString("LighterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light GoldenrodYellow.
        /// </summary>
        internal static string LightGoldenrodYellow {
            get {
                return ResourceManager.GetString("LightGoldenrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Gray.
        /// </summary>
        internal static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        internal static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Pink.
        /// </summary>
        internal static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Salmon.
        /// </summary>
        internal static string LightSalmon {
            get {
                return ResourceManager.GetString("LightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light SeaGreen.
        /// </summary>
        internal static string LightSeaGreen {
            get {
                return ResourceManager.GetString("LightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light SkyBlue.
        /// </summary>
        internal static string LightSkyBlue {
            get {
                return ResourceManager.GetString("LightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light SlateGray.
        /// </summary>
        internal static string LightSlateGray {
            get {
                return ResourceManager.GetString("LightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light SteelBlue.
        /// </summary>
        internal static string LightSteelBlue {
            get {
                return ResourceManager.GetString("LightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightText {
            get {
                return ResourceManager.GetString("LightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Yellow.
        /// </summary>
        internal static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime Green.
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Gradient.
        /// </summary>
        internal static string LinearGradient {
            get {
                return ResourceManager.GetString("LinearGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linen.
        /// </summary>
        internal static string Linen {
            get {
                return ResourceManager.GetString("Linen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Magenta {
            get {
                return ResourceManager.GetString("Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string Margins {
            get {
                return ResourceManager.GetString("Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon.
        /// </summary>
        internal static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string MaximizeTooltip {
            get {
                return ResourceManager.GetString("MaximizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Aquamarine.
        /// </summary>
        internal static string MediumAquamarine {
            get {
                return ResourceManager.GetString("MediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Blue.
        /// </summary>
        internal static string MediumBlue {
            get {
                return ResourceManager.GetString("MediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Orchid.
        /// </summary>
        internal static string MediumOrchid {
            get {
                return ResourceManager.GetString("MediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Purple.
        /// </summary>
        internal static string MediumPurple {
            get {
                return ResourceManager.GetString("MediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium SeaGreen.
        /// </summary>
        internal static string MediumSeaGreen {
            get {
                return ResourceManager.GetString("MediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium SlateBlue.
        /// </summary>
        internal static string MediumSlateBlue {
            get {
                return ResourceManager.GetString("MediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium SpringGreen.
        /// </summary>
        internal static string MediumSpringGreen {
            get {
                return ResourceManager.GetString("MediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Turquoise.
        /// </summary>
        internal static string MediumTurquoise {
            get {
                return ResourceManager.GetString("MediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium VioletRed.
        /// </summary>
        internal static string MediumVioletRed {
            get {
                return ResourceManager.GetString("MediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Blue.
        /// </summary>
        internal static string MidnightBlue {
            get {
                return ResourceManager.GetString("MidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string MinimizeTooltip {
            get {
                return ResourceManager.GetString("MinimizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mint Cream.
        /// </summary>
        internal static string MintCream {
            get {
                return ResourceManager.GetString("MintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misty Rose.
        /// </summary>
        internal static string MistyRose {
            get {
                return ResourceManager.GetString("MistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moccasin.
        /// </summary>
        internal static string Moccasin {
            get {
                return ResourceManager.GetString("Moccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Colors....
        /// </summary>
        internal static string MoreColorsText {
            get {
                return ResourceManager.GetString("MoreColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string MoreColorsWindowTitleText {
            get {
                return ResourceManager.GetString("MoreColorsWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The margins overlap or they are off the paper.
        ///Enter a different margin size..
        /// </summary>
        internal static string msgBoxMargin {
            get {
                return ResourceManager.GetString("msgBoxMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navajo White.
        /// </summary>
        internal static string NavajoWhite {
            get {
                return ResourceManager.GetString("NavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        internal static string NoColorText {
            get {
                return ResourceManager.GetString("NoColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldLace.
        /// </summary>
        internal static string OldLace {
            get {
                return ResourceManager.GetString("OldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive.
        /// </summary>
        internal static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive Drab.
        /// </summary>
        internal static string OliveDrab {
            get {
                return ResourceManager.GetString("OliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive Green.
        /// </summary>
        internal static string OliveGreen {
            get {
                return ResourceManager.GetString("OliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Red.
        /// </summary>
        internal static string OrangeRed {
            get {
                return ResourceManager.GetString("OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid.
        /// </summary>
        internal static string Orchid {
            get {
                return ResourceManager.GetString("Orchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup.
        /// </summary>
        internal static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Goldenrod.
        /// </summary>
        internal static string PaleGoldenrod {
            get {
                return ResourceManager.GetString("PaleGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Green.
        /// </summary>
        internal static string PaleGreen {
            get {
                return ResourceManager.GetString("PaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Turquoise.
        /// </summary>
        internal static string PaleTurquoise {
            get {
                return ResourceManager.GetString("PaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale VioletRed.
        /// </summary>
        internal static string PaleVioletRed {
            get {
                return ResourceManager.GetString("PaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papaya Whip.
        /// </summary>
        internal static string PapayaWhip {
            get {
                return ResourceManager.GetString("PapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peach Puff.
        /// </summary>
        internal static string PeachPuff {
            get {
                return ResourceManager.GetString("PeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periwinkle.
        /// </summary>
        internal static string Periwinkle {
            get {
                return ResourceManager.GetString("Periwinkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru.
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        internal static string Plum {
            get {
                return ResourceManager.GetString("Plum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powder Blue.
        /// </summary>
        internal static string PowderBlue {
            get {
                return ResourceManager.GetString("PowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Paper Sizes.
        /// </summary>
        internal static string Print_MorePaperSizes {
            get {
                return ResourceManager.GetString("Print_MorePaperSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape Orientation.
        /// </summary>
        internal static string Print_Orientation_Landscape {
            get {
                return ResourceManager.GetString("Print_Orientation_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait Orientation.
        /// </summary>
        internal static string Print_Orientation_Portrait {
            get {
                return ResourceManager.GetString("Print_Orientation_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Margins.
        /// </summary>
        internal static string Print_PageMargin_CustomMargin {
            get {
                return ResourceManager.GetString("Print_PageMargin_CustomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string Print_PageMargin_Moderate {
            get {
                return ResourceManager.GetString("Print_PageMargin_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        internal static string Print_PageMargin_Narrow {
            get {
                return ResourceManager.GetString("Print_PageMargin_Narrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Print_PageMargin_Normal {
            get {
                return ResourceManager.GetString("Print_PageMargin_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide.
        /// </summary>
        internal static string Print_PageMargin_Wide {
            get {
                return ResourceManager.GetString("Print_PageMargin_Wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Size.
        /// </summary>
        internal static string Print_PaperSize {
            get {
                return ResourceManager.GetString("Print_PaperSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        internal static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print All Pages.
        /// </summary>
        internal static string PrintPreview_AllPages {
            get {
                return ResourceManager.GetString("PrintPreview_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole thing.
        /// </summary>
        internal static string PrintPreview_AllPages_ToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_AllPages_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collated.
        /// </summary>
        internal static string PrintPreview_Collated {
            get {
                return ResourceManager.GetString("PrintPreview_Collated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        internal static string PrintPreview_Copies {
            get {
                return ResourceManager.GetString("PrintPreview_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Current Page.
        /// </summary>
        internal static string PrintPreview_CurrentPage {
            get {
                return ResourceManager.GetString("PrintPreview_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        internal static string PrintPreview_CurrentPage_ToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_CurrentPage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string PrintPreview_Pages {
            get {
                return ResourceManager.GetString("PrintPreview_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string PrintPreview_Printer {
            get {
                return ResourceManager.GetString("PrintPreview_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string PrintPreview_To {
            get {
                return ResourceManager.GetString("PrintPreview_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncollated.
        /// </summary>
        internal static string PrintPreview_UnCollated {
            get {
                return ResourceManager.GetString("PrintPreview_UnCollated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must be greater than or equal to.
        /// </summary>
        internal static string PrintPreview_UpDown_GreaterThanToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_UpDown_GreaterThanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must be less than or equal to.
        /// </summary>
        internal static string PrintPreview_UpDown_LessThanToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_UpDown_LessThanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must be a positive number.
        /// </summary>
        internal static string PrintPreview_UpDown_NegativeToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_UpDown_NegativeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry cannot contain any characters that are not numeric.
        /// </summary>
        internal static string PrintPreview_UpDown_NonNumericToopTip {
            get {
                return ResourceManager.GetString("PrintPreview_UpDown_NonNumericToopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Print.
        /// </summary>
        internal static string PrintPreview_UserPages {
            get {
                return ResourceManager.GetString("PrintPreview_UserPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter specific pages to print.
        /// </summary>
        internal static string PrintPreview_UserPages_ToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_UserPages_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        internal static string PropertySupport_ExpressionNotProperty_Exception {
            get {
                return ResourceManager.GetString("PropertySupport_ExpressionNotProperty_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        internal static string PropertySupport_NotMemberAccessExpression_Exception {
            get {
                return ResourceManager.GetString("PropertySupport_NotMemberAccessExpression_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property..
        /// </summary>
        internal static string PropertySupport_StaticExpression_Exception {
            get {
                return ResourceManager.GetString("PropertySupport_StaticExpression_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Print.
        /// </summary>
        internal static string QuickPrint {
            get {
                return ResourceManager.GetString("QuickPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Gradient.
        /// </summary>
        internal static string RadialGradient {
            get {
                return ResourceManager.GetString("RadialGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Used.
        /// </summary>
        internal static string RecentlyUsedText {
            get {
                return ResourceManager.GetString("RecentlyUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedTooltipText {
            get {
                return ResourceManager.GetString("RedTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreTooltip {
            get {
                return ResourceManager.GetString("RestoreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        internal static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose.
        /// </summary>
        internal static string Rose {
            get {
                return ResourceManager.GetString("Rose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosy Brown.
        /// </summary>
        internal static string RosyBrown {
            get {
                return ResourceManager.GetString("RosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Blue.
        /// </summary>
        internal static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saddle Brown.
        /// </summary>
        internal static string SaddleBrown {
            get {
                return ResourceManager.GetString("SaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon.
        /// </summary>
        internal static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy Brown.
        /// </summary>
        internal static string SandyBrown {
            get {
                return ResourceManager.GetString("SandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation..
        /// </summary>
        internal static string SaturationTooltipText {
            get {
                return ResourceManager.GetString("SaturationTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Green.
        /// </summary>
        internal static string SeaGreen {
            get {
                return ResourceManager.GetString("SeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeaShell.
        /// </summary>
        internal static string SeaShell {
            get {
                return ResourceManager.GetString("SeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna.
        /// </summary>
        internal static string Sienna {
            get {
                return ResourceManager.GetString("Sienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        internal static string Sky {
            get {
                return ResourceManager.GetString("Sky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Blue.
        /// </summary>
        internal static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Blue.
        /// </summary>
        internal static string SlateBlue {
            get {
                return ResourceManager.GetString("SlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slate Gray.
        /// </summary>
        internal static string SlateGray {
            get {
                return ResourceManager.GetString("SlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Dictionary.
        /// </summary>
        internal static string SpellCheckerAddToDictionaryText {
            get {
                return ResourceManager.GetString("SpellCheckerAddToDictionaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change All.
        /// </summary>
        internal static string SpellCheckerChangeAllText {
            get {
                return ResourceManager.GetString("SpellCheckerChangeAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string SpellCheckerChangeText {
            get {
                return ResourceManager.GetString("SpellCheckerChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SpellCheckerCloseText {
            get {
                return ResourceManager.GetString("SpellCheckerCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Checker.
        /// </summary>
        internal static string SpellCheckerHeaderText {
            get {
                return ResourceManager.GetString("SpellCheckerHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string SpellCheckerIgnoreAllText {
            get {
                return ResourceManager.GetString("SpellCheckerIgnoreAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Once.
        /// </summary>
        internal static string SpellCheckerIgnoreOnceText {
            get {
                return ResourceManager.GetString("SpellCheckerIgnoreOnceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in Dictionary:.
        /// </summary>
        internal static string SpellCheckerNotInDictionaryText {
            get {
                return ResourceManager.GetString("SpellCheckerNotInDictionaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions:.
        /// </summary>
        internal static string SpellCheckerSuggestionsText {
            get {
                return ResourceManager.GetString("SpellCheckerSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpringGreen.
        /// </summary>
        internal static string SpringGreen {
            get {
                return ResourceManager.GetString("SpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colors.
        /// </summary>
        internal static string StandardColorsText {
            get {
                return ResourceManager.GetString("StandardColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string StandardText {
            get {
                return ResourceManager.GetString("StandardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Point.
        /// </summary>
        internal static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelBlue.
        /// </summary>
        internal static string SteelBlue {
            get {
                return ResourceManager.GetString("SteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TanColor.
        /// </summary>
        internal static string TanColor {
            get {
                return ResourceManager.GetString("TanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Colors.
        /// </summary>
        internal static string ThemeColorsText {
            get {
                return ResourceManager.GetString("ThemeColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thistle.
        /// </summary>
        internal static string Thistle {
            get {
                return ResourceManager.GetString("Thistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato.
        /// </summary>
        internal static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownColor.
        /// </summary>
        internal static string UnknownColor {
            get {
                return ResourceManager.GetString("UnknownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value/Brightness..
        /// </summary>
        internal static string ValueTooltipText {
            get {
                return ResourceManager.GetString("ValueTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks in.
        /// </summary>
        internal static string WeekNumbers {
            get {
                return ResourceManager.GetString("WeekNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Smoke.
        /// </summary>
        internal static string WhiteSmoke {
            get {
                return ResourceManager.GetString("WhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Green.
        /// </summary>
        internal static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
    }
}
